name: cursormailer
description: "CursorMailer - Send emails to multiple recipients easily"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mailer: ^6.1.0
  file_picker: ^10.3.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  http: ^1.2.1
  email_validator: ^3.0.0
  flutter_dotenv: ^5.1.0
  animations: ^2.0.11
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env